test {
  common {
    id: "1_TSR1_0A131FDD4001JX"
    description: "Sports_2160P-4aae_horizontal_clip_2_2160_to_1080_V_crf_1"
  }
  input {
    filepath: "Sports_2160P-4aae_horizontal_clip_2_2160_to_1080_V_crf_1.yuv"
    resolution: "1080x1920"
    framerate: 60.0
    realtime: false
    show: false
  }
  configure {
    codec: "com.apple.videotoolbox.videoencoder.h264"
    encode: true
    bitrate: "10000 kbps"
  }
  parallel {
  }
}
